name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo gem install bundler
          bundle config set --local with 'development'
          sudo bundle install
      - name: Run RSpec tests
        run: bundle exec rspec
